# Generated by Django 5.1.5 on 2026-02-23 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Назва підприємства')),
                ('category', models.CharField(choices=[('manufacturer', 'Виробник'), ('retailer', 'Рітейлер'), ('both', 'Виробник і рітейлер')], max_length=20, verbose_name='Категорія')),
                ('details', models.TextField(blank=True, verbose_name='Деталі підприємства')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Локація')),
                ('work_schedule', models.CharField(blank=True, max_length=255, verbose_name='Графік роботи')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактна особа')),
                ('contact_person_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон контактної особи')),
                ('catalog_url', models.URLField(blank=True, verbose_name='Каталог (посилання)')),
                ('comments', models.TextField(blank=True, verbose_name='Коментарі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Постачальник',
                'verbose_name_plural': 'Постачальники',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('confirmed', 'Підтверджено'), ('in_transit', 'В транзиті'), ('received', 'Отримано'), ('delayed', 'Затримується')], default='new', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна сума')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість доставки')),
                ('payment_status', models.CharField(choices=[('not_paid', 'Не оплачено'), ('partially_paid', 'Частково оплачено'), ('paid', 'Оплачено')], default='not_paid', max_length=20, verbose_name='Статус оплати')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Прогнозована дата доставки')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Фактична дата доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='contracts.contract', verbose_name='Договір')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='procurement.supplier', verbose_name='Постачальник')),
            ],
            options={
                'verbose_name': 'Закупівля',
                'verbose_name_plural': 'Закупівлі',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255, verbose_name='Назва матеріалу')),
                ('material_type', models.CharField(blank=True, max_length=100, verbose_name='Тип')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категорія')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Одиниці виміру')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за одиницю')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Загальна ціна')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchase', verbose_name='Закупівля')),
            ],
            options={
                'verbose_name': 'Позиція закупівлі',
                'verbose_name_plural': 'Позиції закупівлі',
            },
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('material_name', models.CharField(max_length=255, verbose_name='Назва матеріалу')),
                ('material_type', models.CharField(blank=True, max_length=100, verbose_name='Тип')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категорія')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Колір')),
                ('ttn', models.CharField(blank=True, max_length=255, verbose_name='ТТН')),
                ('expected_date', models.DateField(verbose_name='Планована дата поставки')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Фактична дата поставки')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('confirmed', 'Підтверджено'), ('in_transit', 'В транзиті'), ('received', 'Отримано'), ('delayed', 'Затримується')], default='new', max_length=20, verbose_name='Статус')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_schedules', to='contracts.contract', verbose_name='Договір')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_schedules', to='procurement.purchase', verbose_name='Закупівля')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.supplier', verbose_name='Постачальник')),
            ],
            options={
                'verbose_name': 'Графік поставки',
                'verbose_name_plural': 'Графік поставок',
                'ordering': ['expected_date'],
            },
        ),
    ]
