# Generated by Django 5.2.11 on 2026-03-03 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_customer_cooperation_form_and_more"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="orders.customer",
                verbose_name="Постачальник",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryschedule",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.customer",
                verbose_name="Постачальник",
            ),
        ),
    ]
