# Generated by Django 5.2.11 on 2026-03-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_alter_purchase_supplier_and_more"),
        ("warehouse", "0003_alter_material_supplier"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
