# Generated by Django 5.1.5 on 2026-02-23 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('ready', 'Готова'), ('sent', 'Надіслана'), ('accepted', 'Прийнята'), ('rejected', 'Відхилена')], default='draft', max_length=20, verbose_name='Статус')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ціна пропозиції')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата відправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Пропозиція',
                'verbose_name_plural': 'Пропозиції',
            },
        ),
    ]
