# Generated by Django 5.1.5 on 2026-02-23 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Завершений успішно'), ('cancelled', 'Скасований'), ('frozen', 'Заморожений')], max_length=20, verbose_name='Статус')),
                ('duration_days', models.PositiveIntegerField(default=0, verbose_name='Тривалість (днів)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Загальна вартість')),
                ('total_produced', models.PositiveIntegerField(default=0, verbose_name='Загальна кількість виробів')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='Архівовано')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archived_project', to='contracts.contract', verbose_name='Договір')),
            ],
            options={
                'verbose_name': 'Архівований проект',
                'verbose_name_plural': 'Архівовані проекти',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва виробу')),
                ('category', models.CharField(choices=[('jacket', 'Куртка'), ('tshirt', 'Футболка'), ('pants', 'Штани'), ('suit', 'Костюм'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Категорія')),
                ('product_type', models.CharField(choices=[('male', 'Чоловіче'), ('female', 'Жіноче'), ('unisex', 'Унісекс')], default='unisex', max_length=20, verbose_name='Тип')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість 1 виробу')),
                ('currency', models.CharField(default='UAH', max_length=10, verbose_name='Валюта')),
                ('production_date', models.DateField(verbose_name='Дата виготовлення')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість виготовлених')),
                ('transferred_to_main', models.BooleanField(default=False, verbose_name='Передано на головний склад')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='Дата переміщення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_products', to='contracts.contract', verbose_name='Договір')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_products', to='accounts.department', verbose_name='Виробничий підрозділ')),
            ],
            options={
                'verbose_name': 'Готовий виріб',
                'verbose_name_plural': 'Готові вироби',
                'ordering': ['-production_date'],
            },
        ),
    ]
