# Generated by Django 5.1.5 on 2026-02-23 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('notification_type', models.CharField(choices=[('task_created', 'Створено нове завдання'), ('checklist_tagged', 'Вас відмічено у чек-лісті'), ('order_created', 'Створено нове замовлення'), ('project_created', 'Створено новий проект'), ('daily_report_reminder', 'Нагадування про щоденний звіт'), ('shipment_docs_reminder', 'Підготуйте документацію для відправки'), ('payment_reminder', 'Нагадування про оплату'), ('request_created', 'Створено новий запит'), ('request_response', 'Отримано відповідь на запит'), ('status_changed', 'Змінено статус'), ('document_added', 'Додано документ'), ('transfer_created', 'Створено переміщення'), ('transfer_accepted', 'Переміщення прийнято'), ('purchase_created', 'Створено закупівлю')], max_length=30, verbose_name='Тип')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Посилання')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отримувач')),
            ],
            options={
                'verbose_name': 'Сповіщення',
                'verbose_name_plural': 'Сповіщення',
                'ordering': ['-created_at'],
            },
        ),
    ]
