# Generated by Django 5.1.5 on 2026-02-23 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категорія')),
                ('pattern_type', models.CharField(choices=[('male', 'Чоловіче'), ('female', 'Жіноче'), ('unisex', 'Унісекс'), ('child', 'Дитяче')], max_length=20, verbose_name='Тип')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('size_range', models.CharField(blank=True, max_length=255, verbose_name='Розмірний ряд')),
                ('file', models.FileField(blank=True, null=True, upload_to='patterns/', verbose_name='Файл викрійки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Лекало',
                'verbose_name_plural': 'Лекала',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул/код')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('material_type', models.CharField(blank=True, max_length=100, verbose_name='Тип')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категорія')),
                ('density', models.CharField(blank=True, max_length=100, verbose_name='Щільність')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Колір')),
                ('is_available', models.BooleanField(default=True, verbose_name='Наявність')),
                ('unit', models.CharField(choices=[('rm', 'м/п'), ('pcs', 'шт'), ('kg', 'кг'), ('lm', 'км/п')], default='rm', max_length=10, verbose_name='Одиниці виміру')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Кількість на складі')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна за 1 одиницю')),
                ('currency', models.CharField(default='UAH', max_length=10, verbose_name='Валюта')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна ціна')),
                ('ttn', models.CharField(blank=True, max_length=255, verbose_name='ТТН')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата замовлення')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата поставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='procurement.supplier', verbose_name='Постачальник')),
            ],
            options={
                'verbose_name': 'Матеріал',
                'verbose_name_plural': 'Матеріали',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('material_to_supplier', 'Повернення матеріалу постачальнику'), ('product_from_customer', 'Повернення виробів від замовника')], max_length=30, verbose_name='Тип повернення')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='Назва виробу')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата закупівлі')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна за одиницю')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна сума')),
                ('ttn_file', models.FileField(blank=True, null=True, upload_to='returns/ttn/', verbose_name='ТТН')),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='returns/receipts/', verbose_name='Квитанція про оплату')),
                ('reason', models.TextField(verbose_name='Причина повернення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='warehouse.material', verbose_name='Матеріал')),
            ],
            options={
                'verbose_name': 'Повернення',
                'verbose_name_plural': 'Повернення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('contact_info', models.TextField(blank=True, verbose_name='Контактна інформація')),
                ('warehouse_type', models.CharField(choices=[('main', 'Головний склад'), ('production_unit', 'Склад виробничого підрозділу')], max_length=30, verbose_name='Тип складу')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Завскладу')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склади',
            },
        ),
        migrations.CreateModel(
            name='ProductTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Назва виробу')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Прийнято')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_product_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Прийняв')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_transfers', to='contracts.contract', verbose_name='Договір')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_product_transfers', to='warehouse.warehouse', verbose_name='Звідки')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_product_transfers', to='warehouse.warehouse', verbose_name='Куди')),
            ],
            options={
                'verbose_name': 'Переміщення виробів',
                'verbose_name_plural': 'Переміщення виробів',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Прийнято')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_material_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Прийняв')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_material_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='warehouse.material', verbose_name='Матеріал')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_material_transfers', to='warehouse.warehouse', verbose_name='Звідки')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_material_transfers', to='warehouse.warehouse', verbose_name='Куди')),
            ],
            options={
                'verbose_name': 'Переміщення матеріалу',
                'verbose_name_plural': 'Переміщення матеріалів',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='warehouse.warehouse', verbose_name='Склад'),
        ),
    ]
