# Generated by Django 5.1.5 on 2026-02-23 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Назва підприємства')),
                ('cooperation_form', models.CharField(choices=[('tender', 'Тендер'), ('direct_order', 'Пряме замовлення'), ('agreement', 'Угода')], max_length=30, verbose_name='Форма співпраці')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_persons', models.JSONField(blank=True, default=list, verbose_name='Контактні особи')),
                ('cooperation_history', models.TextField(blank=True, verbose_name='Історія співпраці')),
            ],
            options={
                'verbose_name': 'Замовник',
                'verbose_name_plural': 'Замовники',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Джерело')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість одиниць')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сума оплати')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Кінцевий термін подачі')),
                ('execution_period', models.CharField(blank=True, max_length=255, verbose_name='Терміни виконання')),
                ('priority', models.CharField(choices=[('high', 'Важливий'), ('medium', 'Середній'), ('low', 'Мінімальний')], default='medium', max_length=10, verbose_name='Пріоритет')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('document_collection', 'Збір документації'), ('bidding', 'В процесі торгів'), ('approved', 'Погоджено'), ('won', 'Перемога'), ('lost', 'Програш'), ('frozen', 'Заморожене'), ('rejected', 'Відхилено')], default='new', max_length=30, verbose_name='Статус')),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Пропонована вартість')),
                ('proposed_term', models.CharField(blank=True, max_length=255, verbose_name='Пропонований термін')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина відхилення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.customer', verbose_name='Замовник')),
                ('participants', models.ManyToManyField(blank=True, related_name='participating_orders', to=settings.AUTH_USER_MODEL, verbose_name='Учасники')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
    ]
