# Generated by Django 5.2.11 on 2026-03-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="cooperation_form",
        ),
        migrations.AddField(
            model_name="customer",
            name="cooperation_forms",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Форми співпраці"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_types",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Типи контрагента"
            ),
        ),
    ]
