# Generated by Django 5.1.5 on 2026-02-23 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('request_type', models.CharField(choices=[('warehouse', 'Запит на склад'), ('patterns', 'Запит на лекала'), ('calculation', 'Запит на прорахунок'), ('procurement', 'Запит на закупівлю')], max_length=20, verbose_name='Тип запиту')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Термін виконання')),
                ('status', models.CharField(choices=[('open', 'Відкритий'), ('closed', 'Закритий')], default='open', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Виконавець')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='contracts.contract', verbose_name='Договір')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Запит',
                'verbose_name_plural': 'Запити',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, verbose_name='Текст відповіді')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дані')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='requests_app.request', verbose_name='Запит')),
            ],
            options={
                'verbose_name': 'Відповідь на запит',
                'verbose_name_plural': 'Відповіді на запити',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='requests_app.request', verbose_name='Запит')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Учасник запиту',
                'verbose_name_plural': 'Учасники запиту',
                'unique_together': {('request', 'user')},
            },
        ),
    ]
