# Generated by Django 5.1.5 on 2026-02-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системна група')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Група дозволів',
                'verbose_name_plural': 'Групи дозволів',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='permission_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.permissiongroup', verbose_name='Група дозволів'),
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Дашборд'), ('orders', 'Замовлення'), ('contracts', 'Договори'), ('warehouse', 'Склад'), ('procurement', 'Закупівлі'), ('production', 'Виробництво'), ('tasks', 'Завдання'), ('requests', 'Запити'), ('chat', 'Чат'), ('notifications', 'Сповіщення'), ('analytics', 'Аналітика'), ('users', 'Користувачі'), ('directories', 'Довідники'), ('tech_specs', 'Тех. специфікації')], max_length=30, verbose_name='Модуль')),
                ('can_view', models.BooleanField(default=False, verbose_name='Перегляд')),
                ('can_create', models.BooleanField(default=False, verbose_name='Створення')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Редагування')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Видалення')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='accounts.permissiongroup', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Дозвіл модуля',
                'verbose_name_plural': 'Дозволи модулів',
                'ordering': ['module'],
                'unique_together': {('group', 'module')},
            },
        ),
    ]
