# Generated by Django 5.1.5 on 2026-02-23 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID обʼєкта')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Завантажено')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип обʼєкта')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Завантажив')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='documents_d_content_ba3031_idx')],
            },
        ),
    ]
