# Generated by Django 5.1.5 on 2026-02-23 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Приналежність',
                'verbose_name_plural': 'Приналежності',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Дата введення в дію')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення дії')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('active', 'Діючий'), ('expired', 'Недіючий'), ('cancelled', 'Скасований')], default='draft', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to='tech_specs/', verbose_name='Документ')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specifications', to='documents.affiliation', verbose_name='Приналежність')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tech_specs', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Технічна специфікація',
                'verbose_name_plural': 'Технічні специфікації',
                'ordering': ['-created_at'],
            },
        ),
    ]
