# Generated by Django 5.1.5 on 2026-02-23 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='calculations/', verbose_name='Файл калькуляції')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версія')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='contracts.contract', verbose_name='Договір')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Калькуляція',
                'verbose_name_plural': 'Калькуляції',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255, verbose_name='Назва матеріалу')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Колір')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Одиниці виміру')),
                ('consumption_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Розхід на одиницю')),
                ('multiplication_coefficient', models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Коефіцієнт збільшення')),
                ('total_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума на одиницю')),
                ('total_per_batch', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сума на партію')),
                ('price_with_vat_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна за одиницю з ПДВ')),
                ('price_with_vat_batch', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ціна за партію з ПДВ')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Дата відгрузки')),
                ('comments', models.TextField(blank=True, verbose_name='Коментарі')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculations.calculation', verbose_name='Калькуляція')),
            ],
            options={
                'verbose_name': 'Позиція калькуляції',
                'verbose_name_plural': 'Позиції калькуляції',
            },
        ),
    ]
