# Generated by Django 5.1.5 on 2026-02-23 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='Номер договору')),
                ('status', models.CharField(choices=[('planning', 'Планування'), ('production', 'Виробництво'), ('completed', 'Завершений'), ('frozen', 'Заморожений / скасований')], default='planning', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Кінцевий термін')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Загальна кількість виробів')),
                ('specification', models.TextField(blank=True, verbose_name='Специфікація')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='orders.order', verbose_name='Замовлення')),
                ('participants', models.ManyToManyField(blank=True, related_name='participating_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Учасники')),
            ],
            options={
                'verbose_name': 'Актуальний договір',
                'verbose_name_plural': 'Актуальні договори',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Назва виробу')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість виробів')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='contracts.contract', verbose_name='Договір')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='accounts.department', verbose_name='Підрозділ')),
            ],
            options={
                'verbose_name': 'Щоденний звіт виробництва',
                'verbose_name_plural': 'Щоденні звіти виробництва',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(default=0, verbose_name='Обсяг виробів')),
                ('schedule_file', models.FileField(blank=True, null=True, upload_to='production_plans/', verbose_name='Файл графіку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='contracts.contract', verbose_name='Договір')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='accounts.department', verbose_name='Підрозділ')),
            ],
            options={
                'verbose_name': 'План виробництва',
                'verbose_name_plural': 'Плани виробництва',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Назва виробу')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('ship_date', models.DateField(verbose_name='Дата відправки')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_transit', 'В транзиті'), ('paid', 'Оплачено'), ('completed', 'Завершено')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='contracts.contract', verbose_name='Договір')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Відправка',
                'verbose_name_plural': 'Відправки',
                'ordering': ['-ship_date'],
            },
        ),
    ]
